# Generated by Django 4.0 on 2023-11-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_partner_amount_partner_plegde_alter_partner_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='plegde',
            new_name='pledge',
        ),
    ]
