# Generated by Django 4.0 on 2023-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('method_of_teaching', models.CharField(default='Online', max_length=50)),
                ('duration', models.CharField(default='', max_length=200)),
                ('number_of_lessons', models.IntegerField()),
                ('payment', models.CharField(default='$', max_length=50)),
                ('app', models.CharField(default='Zoom', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_testimonials', models.IntegerField()),
                ('number_of_instructors', models.IntegerField()),
            ],
        ),
    ]
