# Generated by Django 4.0 on 2023-11-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('summary_of_testimoney', models.TextField()),
            ],
        ),
    ]
