# Generated by Django 4.0 on 2023-11-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('expectation', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
